### ISSUE TITLE
Cannot fine ".xauth" file

### ISSUE THREAD

**Issue by Egbert-518** [reflector-li/autoware_universe#1]
Hello, I'm appreciate your work! However,  when I tried to search the ".xauth" file, I cannot get the result. Do you have encountered this problem! Looking forward your apply!

**Comment by stevenk12** [comment]
I 'm also looking forward to your answer!!

**Comment by Egbert-518** [comment]
> I 'm also looking forward to your answer!!

You can try "find /var/lib/docker -name <your .xauth-file-name>" to localize your file.
